/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fm;

import Classes.FinanceManager;
import com.mycompany.purchasemanager.*;
import javax.swing.table.DefaultTableModel;
import Classes.purchaseOrder;

import Classes.purchaseOrder;

/**
 *
 * @author abdul
 */
public class ViewPOsFrame extends javax.swing.JFrame {

    private FinanceManager fm;
    public ViewPOsFrame() {
        initComponents();
       loadItemsIntoTable();
     
    }

private void loadItemsIntoTable() {
    purchaseOrder o = new purchaseOrder();
    DefaultTableModel allItemsModel = o.displayAll();
    DefaultTableModel filteredModel = new DefaultTableModel();

    // Set column identifiers for the table
    filteredModel.setColumnIdentifiers(new Object[]{
        "PO ID", "Date", "Supplier ID", "Item ID", "Quantity", "Total Amount", "Status"
    });

    // Filter out "Paid" POs and add the rest to the filtered model
    for (int i = 0; i < allItemsModel.getRowCount(); i++) {
        String status = allItemsModel.getValueAt(i, 6).toString(); // Assuming "Status" is in the 7th column
        if (!"Paid".equalsIgnoreCase(status)) { // Exclude rows with "Paid" status
            filteredModel.addRow(new Object[]{
                allItemsModel.getValueAt(i, 0), // PO ID
                allItemsModel.getValueAt(i, 1), // Date
                allItemsModel.getValueAt(i, 2), // Supplier ID
                allItemsModel.getValueAt(i, 3), // Item ID
                allItemsModel.getValueAt(i, 4), // Quantity
                allItemsModel.getValueAt(i, 5), // Total Amount
                status // Status
            });
        }
    }

    // Set the filtered model to the table
    loadItemsIntoTable.setModel(filteredModel);
}


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        loadItemsIntoTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        loadItemsIntoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        loadItemsIntoTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                loadItemsIntoTableComponentShown(evt);
            }
        });
        loadItemsIntoTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                loadItemsIntoTablePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(loadItemsIntoTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("View POs Frame");

        closeButton.setText("Back");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadItemsIntoTableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_loadItemsIntoTableComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_loadItemsIntoTableComponentShown

    private void loadItemsIntoTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_loadItemsIntoTablePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_loadItemsIntoTablePropertyChange

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
    closeButton.addActionListener(e -> dispose());        // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPOsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPOsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPOsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPOsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPOsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable loadItemsIntoTable;
    // End of variables declaration//GEN-END:variables
}
