/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Classes.FinanceManager;
import Classes.Login;
import GUI.SalesManagerDashboard;
import IMGUI.InventoryManagerGUI;
import javax.swing.JOptionPane;
import com.mycompany.purchasemanager.purchaseManagerMain;
import fm.FinanceManagerGUI;


/**
 *
 * @author Hp
 */
public class LoginFrame extends javax.swing.JFrame {
    private int loginAttempts = 0; // Counter to track login attempts
    private static String loggedInUserId; // Variable to store the logged-in user ID
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lUsername = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        lUsername.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lUsername.setText("Username:");

        lPassword.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lPassword.setText("Password");

        loginBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lUsername)
                            .addComponent(lPassword))
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(tfPassword))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUsername)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPassword)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String username = tfUsername.getText();
        String password = tfPassword.getText();

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Login login = new Login();
        String result = login.determineRole(username, password);
        
        if (result.equals("Invalid username or password.")){
            loginAttempts++; // Increment login attempts
        if (loginAttempts >= 3) {
                JOptionPane.showMessageDialog(this, "Too many failed attempts. You cannot login anymore.", "Login Failed", JOptionPane.ERROR_MESSAGE);
                loginBtn.setEnabled(false); // Disable login button
                return;
            }
            JOptionPane.showMessageDialog(this, "Invalid username or password. Attempt " + loginAttempts + " of 3.", "Login Failed", JOptionPane.ERROR_MESSAGE);
        } else {
            // Set the logged-in user ID upon successful login
            loggedInUserId = login.getLoggedInUserId(username); // Retrieve the user ID
            loginAttempts = 0; // Reset login attempts

            switch (result) {
                case "Sales Manager" ->{
                    JOptionPane.showMessageDialog(this, "Welcome Sales Manager!", "Login Successful", JOptionPane.INFORMATION_MESSAGE);
                    SalesManagerDashboard SM =  new SalesManagerDashboard(result);
                    SM.setVisible(true);
                    this.dispose();
                    
                }
                case "Purchase Manager" -> {
                    JOptionPane.showMessageDialog(this, "Welcome Purchase Manager!", "Login Successful", JOptionPane.INFORMATION_MESSAGE);
                    purchaseManagerMain PMM = new purchaseManagerMain(result);
                    PMM.setVisible(true);
                    this.dispose();
                }
                case "Finance Manager" ->{ 
                    JOptionPane.showMessageDialog(this, "Welcome Finance Manager!", "Login Successful", JOptionPane.INFORMATION_MESSAGE);
                    FinanceManager fm = null;
                    FinanceManagerGUI FMG = new FinanceManagerGUI(fm, result);
                    FMG.setVisible(true);
                    this.dispose();
                }
                case "Inventory Manager" ->{
                    JOptionPane.showMessageDialog(this, "Welcome Inventory Manager!", "Login Successful", JOptionPane.INFORMATION_MESSAGE);
                    InventoryManagerGUI IMG = new InventoryManagerGUI(result);
                    IMG.setVisible(true);
                    this.dispose();
                }
                case "Administrator" -> {
                    JOptionPane.showMessageDialog(this, "Welcome Administrator!", "Login Successful", JOptionPane.INFORMATION_MESSAGE);
                    AdminFrame adminFrame = new AdminFrame(); // Instantiate AdminFrame
                    adminFrame.setVisible(true); // Show AdminFrame
                    this.dispose(); // Close the LoginFrame
                }

                default -> JOptionPane.showMessageDialog(this, result, "Login Failed", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    public static String getLoggedInUserId() {
        return loggedInUserId;
    }
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lUsername;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}





